### ISSUE TITLE
Provide interface for adding attachments to e-mail

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.eventmessages#11]
We want internal and external users of the eventmessages to also define attached files. For that we will:

- implement an interface to **register** (and **provide**, if requested) attachment files with the token processor in a similar way as the tokens.
- implement an "example" attachment provider that generates an ``.ical`` event file
- extend the eventmessages configuration to allow the user to chose one or more from the available attachments for each rule. This also requires an update of the ``civicrm_event_message_rules`` table and the access abstraction (which are not BAOs in this case).

**Comment by jensschuppe** [comment]
This has been refactored to use the [Mail Attachments](https://github.com/systopia/de.systopia.mailattachment) extension which allows for all participant-based attachment types to be used.

Also, the attachment types previously included within Event Communication, _iCal_ and _PDF Message Template_ have been migrated to Mail Attachments's structure.

All this is being developed in the `feature/mailAttachments` branch.
