### ISSUE TITLE
Add template_id into Event.create API

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.eventmessages#22]
If ``Event.create`` is called via the API with no ``id`` but a ``template_id`` given, the referenced template should be cloned (in particular to copy the event message configuration) and then the ``id`` set before passed on.

This way, a API based importer should allow using templates.

Tag @zfranque

**Comment by bjendres** [comment]
@zfranque could you please test the attached version? [de.systopia.eventmessages-1.1-dev+9b32849fc0759.tar.gz](https://github.com/systopia/de.systopia.eventmessages/files/8727246/de.systopia.eventmessages-1.1-dev%2B9b32849fc0759.tar.gz)

**Comment by bjendres** [comment]
there was still an issue with [#11], try the attached version:
[de.systopia.eventmessages-1.1-dev+b916bda9866986b.tar.gz](https://github.com/systopia/de.systopia.eventmessages/files/8727494/de.systopia.eventmessages-1.1-dev%2Bb916bda9866986b.tar.gz)

**Comment by zfranque** [comment]
your the best @bjendres, it works fine now.

The "template_id" shows now in APIv3 & APIv4 and I can use it in the API csv importer to copy all content including the Communication Settings from a given event template.

**Comment by jensschuppe** [comment]
@bjendres I suppose we can delete the open branch `issue/22`?
