### ISSUE TITLE
Fill 'currently submitted' custom tokens

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.eventmessages#31]
Since #9 doesn't seem to have done the trick, we want to:

- add ``custom_xx`` values in the submission to override any given custom fields (that are subject to the problems described in issue #9)
- add a setting to actively enable this behaviour - so we don't break any working configurations

**Comment by jojowork** [comment]
The extension has been tested by me and the client. It is working as expected (and can be released).

**Comment by bjendres** [comment]
> The extension has been tested by me and the client. It is working as expected (and can be released).

That's great! Should we also include #32 in the release?

**Comment by jofranz** [comment]
@bjendres Would be awesome if this could get at least into `master` as there is a customer who seems to be struggling with this problem.

_ref.: 21976_

**Comment by jojowork** [comment]
we need a release version of event-messages with this feature, because otherwise a client can not update event message communication extension anymore - which is currently planned.
