### ISSUE TITLE
Add option to generate UTC ical files

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.eventmessages#36]
It seems that some systems (e.g. [Kopano](https://kopano.com/)) cannot process the current timezone/time format in the ``.ical`` files, like this:
```
DTSTAMP;TZID=Europe/Berlin:20230724T044248
```
Instead it expects UTC time like this:
```
DTSTAMP:20230724T044248Z
```

We'd want to either:

- add an configuration option to EventMessages (or CiviCRM?) to change change the default behaviour, or
- provide the option to chose the required format with each event message template

**Comment by jensschuppe** [comment]
@bjendres Since this is marked *wontfix*, can we remove the branches named `issue/36` and `issue/36_restart`?
