### ISSUE TITLE
Some configuration options (e.g. sender) broken since 1.1-beta4

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.eventmessages#37]
Some EM features are broken since [628c54f096](https://github.com/systopia/de.systopia.eventmessages/commit/628c54f0969485172a98b710dd6961480b6a5a06), which was released with version ``1.1-beta4``.

Those features are:
- selecting the sender
- selecting the replyTo
- selecting the CC
- selecting the BCC

The reason is that in that context, the "Custom-Data-Helper" plugin accidentally(?) dropped the ``$separator`` parameter in the ``labelCustomFields`` and the ``getFieldIdentifier`` helper functions.

We should re-instate this and release a fix for the 1.1 and the 1.2 branch.

**Comment by bjendres** [comment]
The current default notification is ``group_name.field_name``, but we cannot simply change the default behaviour since it also affects tokens in the outgoing mails

**Comment by jensschuppe** [comment]
The `$separator` parameter apparently never made it into CustomDataHelper; it was introduced here with 0409d12b2bac7bad6494f9ef514acecc29f84f89.
