### ISSUE TITLE
provide API for Rules

### ISSUE THREAD

**Issue by jojowork** [systopia/de.systopia.eventmessages#41]
It is possible to import/export Events of type template via APIv4.
But the EventMessage-Rules are not available via API.
To be able to import/export EventMessage-Rules an APIv4 Endpoint is necessary for them.

**Comment by jojowork** [comment]
provided an PR #42

**Comment by jensschuppe** [comment]
Thanks, @jojowork! I don't think we need a separate issue though, let's discuss things in the PR instead - makes housekeeping easier.
