### ISSUE TITLE
Tokens for custom field values not filled when message is sent during registration

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.eventmessages#9]
It seems that while the participant's general data is available as a token when triggering the message through CiviCRM's native registration form.

The reason is very likely that the post-hook is triggered before the custom data is written, and we need to implement a callback.

**Comment by bjendres** [comment]
Good news here: @jaapjansma has hit the same issue with [civirules#142](https://lab.civicrm.org/extensions/civirules/-/issues/142), and created [CORE-2948](https://lab.civicrm.org/dev/core/-/issues/2948), along with a PR. If we're lucky this problem here will then go away as well.

**Comment by jaapjansma** [comment]
This is going to be solved in CiviCRM version 5.45.0

**Comment by jensschuppe** [comment]
@bjendres or @jaapjansma Anything left to be done here (e.g. denote Core version requirement in `info.xml`)? Can the branches `issue/9` and `issue/9_2` be deleted?

**Comment by jaapjansma** [comment]
Sorry this is to long ago for me to remember anything useful.

**Comment by bjendres** [comment]
> @bjendres or @jaapjansma Anything left to be done here (e.g. denote Core version requirement in `info.xml`)? Can the branches `issue/9` and `issue/9_2` be deleted?

Those were two incomplete and untested attempts to circumnavigate the issue without changing core. There were some interesting concepts there, so I don't want to completely lose them. But I attached them here as patch files, so we can delete the branches to keep the tree clean. @jensschuppe is that ok with you?

[issue_9_2.patch.txt](https://github.com/systopia/de.systopia.eventmessages/files/8553292/issue_9_2.patch.txt)
[issue_9.patch.txt](https://github.com/systopia/de.systopia.eventmessages/files/8553295/issue_9.patch.txt)

**Comment by jensschuppe** [comment]
Thanks, @bjendres, I'm closing this issue and will delete those branches.
